title:             SYNX.io
email:             johnzballad@gmail.com
description:       Um blog de Internet das Coisas
author:            Jonathan Galdino
baseurl:           "/blog"
url:               "http://johnzballad.github.io"

# Social Profiles
twitter_username:  johnzballad
github_username:   JohnzBallad

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
